config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  ActiveAdmin.routes(self)

  resources :jobs do
    resources :conversations do
      resources :messages
    end
  end


  resources :companies do
    patch :update_profile
    patch :update_cover
  end

  resources :users do
    put :verify
    put :send_verification_code
    put :update_language
    patch :deactivate
    patch :update_profile
    patch :update_cover
    get :conversations
    get :categories_users
    put :categories_industries
    put :update_settings

    resources :industries
    resources :categories do
      put :categories_users
    end
    resources :companies do
      patch :update_profile
      patch :update_cover
    end
    resources :jobs do
      collection do
        get :applied_jobs
        get :recommended_jobs
        get :searches
      end
      put :apply
      resources :conversations do
        resources :messages
      end
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  after_create_commit { MessageBroadcastJob.perform_now self }
  def as_json(options = nil)
    super({ only: [:id, :message_body,:message_type,:conversation_id, :user_id]}.merge(options || {}))
  end
end

app/controllers/messages_controller.rb
class MessagesController < InheritedResources::Base
  before_action :authenticate_user!, if: Proc.new { |c| c.request.format != 'application/json' }
  before_action :authenticate_api_user!, if: Proc.new { |c| c.request.format == 'application/json' }
  before_action :get_job
  before_action :get_conversation
  before_action :validate_message, only: [:show, :update, :destroy]

  private

  def validate_message
    message = Message.where(id: params[:id]).first
    render json: {success: false, message: "Message not found!"},status: 401 unless message
  end

  def get_job
    if current_user.has_role? User::ROLES[:employee]
      @job = Job.joins(:employee_jobs).where("jobs.id = ? AND employee_jobs.employee_id = ?", params[:job_id], current_user.id).first
    elsif current_user.has_role? User::ROLES[:employer]
      @job = current_user.jobs.joins(:employee_jobs).where(id: params[:job_id]).first
    end
    unless @job
      message = "Job not found!"
      respond_to do |format|
        format.html {
          flash[:error] = message
          redirect_to  root_path
        }
        format.json { render json: {success: false, messsage: message }, status: 401 }
      end
    end
  end

  def get_conversation
    @conversation = @job.conversations.where(id: params[:conversation_id]).first
    unless @conversation
      message = "Conversation not found!"
      respond_to do |format|
        format.html {
          flash[:error] = message
          redirect_to  root_path
        }
        format.json { render json: {success: false, messsage: message}, status: 401 }
      end
    end
  end

  def message_params
    params.require(:message).permit(:message_body, :message_type).merge(conversation_id: params[:conversation_id], user_id: current_user.id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_with(model: message, url:(message.persisted? ? job_conversation_message_url(message.conversation.job, message.conversation, message) : job_conversation_messages_url), local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :message_body %>
    <%= form.text_area :message_body, id: :message_message_body %>
  </div>

  <div class="field">
    <%= form.label :message_type %>
    <%= form.number_field :message_type, id: :message_message_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_message.html.erb
<tr class="<%= message.user == current_user ? 'bg-info' : '' %>">
  <td><%= message.message_body %></td>
  <td><%= message.message_type %></td>
  <td><%= message.conversation.id %></td>
  <td><%= message.user.email || message.user.phone %></td>
  <td><%= link_to 'Show', job_conversation_message_path(message.conversation.job, message.conversation, message) %></td>
  <td><%= link_to 'Edit', edit_job_conversation_message_path(message.conversation.job, message.conversation, message) %></td>
  <td><%= link_to 'Destroy', job_conversation_message_path(message.conversation.job, message.conversation, message), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', job_conversation_message_path(@message.conversation.job, @message.conversation, @message) %> |
<%= link_to 'Back', job_conversation_messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Message body</th>
      <th>Message type</th>
      <th>Conversation</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="conversation-<%= @conversation.id %>">
    <%= render partial: "message", collection: @messages %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_job_conversation_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', job_conversation_messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message body:</strong>
  <%= @message.message_body %>
</p>

<p>
  <strong>Message type:</strong>
  <%= @message.message_type %>
</p>

<p>
  <strong>Conversation:</strong>
  <%= @message.conversation %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user %>
</p>

<%= link_to 'Edit', edit_job_conversation_message_path(@message.conversation.job, @message.conversation, @message) %> |
<%= link_to 'Back', job_conversation_messages_path %>