config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  ActiveAdmin.routes(self)

  resources :jobs do
    resources :conversations do
      resources :messages
    end
  end


  resources :companies do
    patch :update_profile
    patch :update_cover
  end

  resources :users do
    put :verify
    put :send_verification_code
    put :update_language
    patch :deactivate
    patch :update_profile
    patch :update_cover
    get :conversations
    get :categories_users
    put :categories_industries
    put :update_settings

    resources :industries
    resources :categories do
      put :categories_users
    end
    resources :companies do
      patch :update_profile
      patch :update_cover
    end
    resources :jobs do
      collection do
        get :applied_jobs
        get :recommended_jobs
        get :searches
      end
      put :apply
      resources :conversations do
        resources :messages
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="panel panel-success">
    <div class="panel-heading">
      <% if user_signed_in? %>
          <% if current_user.role_id == User::ROLES[:employee] %>
              <h1 ng-if="name"><%= t :welcome_employee%></h1>
          <% else %>
              <h1 ng-if="name"><%= t :welcome_employer%></h1>
          <%end%>
      <% end %>
    </div>
    <div class="panel-body">
      <% if user_signed_in? %>
          <li><%= link_to('Logout', destroy_user_session_path, method: :delete) %></li>
          <li><%= link_to 'Companies', companies_path %></li>
          <li><%= link_to 'Convesations', user_conversations_path(current_user) %></li>
          <li><%= link_to 'Applied Jobs', applied_jobs_user_jobs_path(current_user) %></li>
          <li><%= link_to 'All Jobs', user_jobs_path(current_user) %></li>
          <li><%= link_to 'Recommended Jobs', recommended_jobs_user_jobs_path(current_user) %></li>
      <% else %>
          <li>
            <%= link_to('Login', new_user_session_path)  %>
          </li>
      <% end %>
    </div>
  </div>
  <%= form_tag((user_update_language_path(current_user)), {:method => :put}) do %>
      <%= select_tag :new_locale, options_for_select(I18n.available_locales, I18n.locale), :onchange => "this.form.submit();" %>
  <% end %>
</div>