config/routes.rb
Rails.application.routes.draw do

  mount ActionCable.server => '/cable'

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  ActiveAdmin.routes(self)

  resources :jobs do
    resources :conversations do
      resources :messages
    end
  end


  resources :companies do
    patch :update_profile
    patch :update_cover
  end

  resources :users do
    put :verify
    put :send_verification_code
    put :update_language
    patch :deactivate
    patch :update_profile
    patch :update_cover
    get :conversations
    get :categories_users
    put :categories_industries
    put :update_settings

    resources :industries
    resources :categories do
      put :categories_users
    end
    resources :companies do
      patch :update_profile
      patch :update_cover
    end
    resources :jobs do
      collection do
        get :applied_jobs
        get :recommended_jobs
        get :searches
      end
      put :apply
      resources :conversations do
        resources :messages
      end
    end
  end
end

app/models/industry.rb
class Industry < ApplicationRecord

  validates :title, presence: true
  has_many :categories
  has_one_attached :picture
  has_and_belongs_to_many :users, -> { distinct }

  scope :with_eager_loaded_picture, -> { eager_load(picture_attachment: :blob) }
  scope :with_preloaded_picture, -> { preload(picture_attachment: :blob) }


  self.per_page = 10

  def self.search(search, page)
    includes(:categories).where(
        "categories.title iLIKE ? OR industries.title iLIKE ?", "%#{search[:key]}%", "%#{search[:key]}%"
    ).references(:categories).order('industries.created_at DESC').page(page)
  end

  def picture_url
    picture.attached? ? picture.service_url : "/assets/default.jpg"
  end

  def as_json(options = nil)
    super({
            only: [:id, :title],
            methods: [:picture_url],
            include: [
                :categories=>{
                    only: [:id, :title, :industry_id],
                    methods: [:picture_url]
                }
            ]
          }.merge(options || {}))
  end
end

app/controllers/industries_controller.rb
class IndustriesController < InheritedResources::Base
  before_action :authenticate_user!, if: Proc.new { |c| c.request.format != 'application/json' }
  before_action :authenticate_api_user!, if: Proc.new { |c| c.request.format == 'application/json' }
  after_action :create_candidate_searches, only: :index

  def index
    @search = {key: params[:key]}
    @industries = Industry.search(@search, params[:page])
    respond_to do |format|
      format.html { @industries || root_path }
      format.json { render json: @industries.as_json }
    end
  end
  private

    def create_candidate_searches
      current_user.searches.create(@search) if @search[:key].present?
    end

    def industry_params
      params.require(:industry).permit(:title)
    end
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/views/industries/_form.html.erb
<%= form_with(model: industry, local: true) do |form| %>
  <% if industry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(industry.errors.count, "error") %> prohibited this industry from being saved:</h2>

      <ul>
      <% industry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/industries/edit.html.erb
<h1>Editing Industry</h1>

<%= render 'form', industry: @industry %>

<%= link_to 'Show', @industry %> |
<%= link_to 'Back', industries_path %>

app/views/industries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Industries</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @industries.each do |industry| %>
      <tr>
        <td><%= industry.title %></td>
        <td><%= link_to 'Show', industry %></td>
        <td><%= link_to 'Edit', edit_industry_path(industry) %></td>
        <td><%= link_to 'Destroy', industry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Industry', new_industry_path %>

app/views/industries/new.html.erb
<h1>New Industry</h1>

<%= render 'form', industry: @industry %>

<%= link_to 'Back', industries_path %>

app/views/industries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @industry.title %>
</p>

<%= link_to 'Edit', edit_industry_path(@industry) %> |
<%= link_to 'Back', industries_path %>